### ISSUE TITLE
MAS 8.11.5 installation using mas-cli is failing at the app-cfg-manage

### ISSUE THREAD

**Issue by ekambaraml** [ibm-mas/ansible-devops#1155]
Here is the mas cli command used for installing the components.

```
mas install --mas-catalog-version v8-amd64 --accept-license \
  --license-file /home/masconfig/entitlement.lic \
  --uds-email 'ekambara@us.ibm.com' --uds-firstname 'Lakshmana' --uds-lastname 'Ekambaram' \
  --storage-rwo 'ocs-storagecluster-ceph-rbd' --storage-rwx 'ocs-storagecluster-cephfs' --storage-pipeline 'ocs-storagecluster-cephfs' --storage-accessmode 'ReadWriteMany' \
  --mas-instance-id 'dev' --mas-workspace-id 'dev' --mas-workspace-name 'dev' \
  --mas-channel '8.11.x' \
  --iot-channel 8.8.x \
  --monitor-channel 8.11.x \
  --manage-channel 8.7.x \
  --manage-jdbc workspace-application --manage-components base=latest,health=latest --manage-demodata \
  --predict-channel 8.9.x \
  --assist-channel 8.8.x \
  --visualinspection-channel 8.9.x \
  --optimizer-channel 8.5.x --optimizer-plan full \
  --kafka-provider strimzi --kafka-version 3.5.1 \
  --db2u-channel v110508.0 --db2u-system --db2u-manage \
  --db2u-cpu-request 4000m --db2u-cpu-limit 6000m --db2u-memory-request 8Gi --db2u-memory-limit 12Gi \
  --db2u-backup-storage 100Gi --db2u-data-storage 100Gi --db2u-logs-storage 100Gi --db2u-meta-storage 20Gi --db2u-temp-storage 100Gi
```

<img width="1721" alt="image" src="https://github.com/ibm-mas/ansible-devops/assets/26153008/33eac951-acfa-4857-9c4b-5f656931df91">

Here are the pod logs of app-cfg-manange pipeline task

[app-cfg-manage.log](https://github.com/ibm-mas/ansible-devops/files/13816969/app-cfg-manage.log)

**DB2 pod log of MAS Manage:**

[c-mas-dev-dev-manage-db2u-0-db2u.log](https://github.com/ibm-mas/ansible-devops/files/13816973/c-mas-dev-dev-manage-db2u-0-db2u.log)
```
+ set +x
{"level":"info","result":"stdout: Waiting for up to 180 sec until a change is detected in the relevant configmaps... change detected\n(*) Applying Db2 registry variables\ndb2set DB2AUTH=OSAUTHDB,ALLOW_LOCAL_FALLBACK,PLUGIN_AUTO_RELOAD\ndb2set DB2_4K_DEVICE_SUPPORT=ON\ndb2set DB2_ATS_ENABLE=YES\ndb2set DB2_BCKP_PAGE_VERIFICATION=TRUE\ndb2set DB2_CDE_DCC=\"\"\ndb2set DB2_CDE_REDUCED_LOGGING=REDUCED_REDO:NO\ndb2set DB2_DCC_BINARY_FILE=\"\"\ndb2set DB2_DCC_FILE_CHUNKSZ=\"\"\ndb2set DB2_DCC_FILE_DEL_THRES=\"\"\ndb2set DB2_DCC_FILE_INS_THRES=\"\"\ndb2set DB2_DCC_FILE_PATH=\"\"\ndb2set DB2_EVALUNCOMMITTED=YES\ndb2set DB2_FMP_COMM_HEAPSZ=65536\ndb2set DB2_FMP_RUN_AS_CONNECTED_USER=NO\ndb2set DB2_INLIST_TO_NLJN=YES\ndb2set DB2_LOAD_COPY_NO_OVERRIDE=COPY YES TO /mnt/bludata0/db2/copy\ndb2set DB2_MINIMIZE_LISTPREFETCH=Y\ndb2set DB2_OBJECT_STORAGE_LOCAL_STAGING_PATH=/mnt/backup/staging\ndb2set DB2_OBJECT_TABLE_ENTRIES=65532\ndb2set DB2_REMOTE_EXTTAB_PIPE_PATH=/db2u/tmp\ndb2set DB2_RESTORE_GRANT_ADMIN_AUTHORITIES=ON\nd...
{"level":"info","result":"stdout: Waiting for up to 180 sec until a change is detected in the relevant configmaps... change detected\n(*) Applying Db2 dbm cfg parameters\nupdate dbm cfg using AGENT_STACK_SZ 1024 AUTHENTICATION SERVER_ENCRYPT CONN_ELAPSE 60 DIAGPATH '/mnt/blumeta0/db2/log $N' DIAGSIZE 300 DISCOVER DISABLE DISCOVER_INST DISABLE FENCED_POOL 50 HEALTH_MON OFF INSTANCE_USAGE DASHDB JDK_PATH /mnt/blumeta0/home/db2inst1/sqllib/java/jdk64 KEEPFENCED NO MAX_CONNRETRIES 5 MON_HEAP_SZ AUTOMATIC NUMDB 1 PYTHON_PATH /usr/bin/python RQRIOBLK 65535\nDB20000I The UPDATE DATABASE MANAGER CONFIGURATION command completed \nsuccessfully.\n\nWolverine HA management state was disabled successfully.\nRunning db2stop force\n01/03/2024 05:14:39 0 0 SQL1064N DB2STOP processing was successful.\nSQL1064N DB2STOP processing was successful.\n \nApplication ipclean: Removing all IPC resources for db2inst1(500)\nc-mas-dev-dev-manage-db2u-0.c-mas-dev-dev-manage-db2u-internal: ipclean -a completed ok\nRunning d...
{"level":"error","component":"server","subComponent":"GetDb2Health","caller":"[13]:db2.go:262:GetDb2Health()","timestamp":"2024-01-03T05:15:06Z","message":"1 MLNs found in MLN dist file, but only 0 db2sysc processes match"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T05:21:10Z","message":"failed to remove expired locks"}
{"level":"info","result":"stdout: Waiting for up to 180 sec until a change is detected in the relevant configmaps... change detected\n(*) Applying DB cfg settings\nParameters that require updating: AUTHN_CACHE_DURATION AUTHN_CACHE_USERS AUTO_DB_BACKUP AUTO_MAINT AUTO_REORG AUTO_REVAL AUTO_RUNSTATS AUTO_TBL_MAINT CATALOGCACHE_SZ CHNGPGS_THRESH CUR_COMMIT DATABASE_MEMORY DBHEAP DDL_CONSTRAINT_DEF DEC_TO_CHAR_FMT DFT_QUERYOPT LOCKLIST LOCKTIMEOUT LOGARCHMETH1 LOGBUFSZ LOGFILSIZ LOGPRIMARY LOGSECOND MAXFILOP MIRRORLOGPATH NUM_DB_BACKUPS NUM_IOCLEANERS NUM_IOSERVERS PCKCACHESZ REC_HIS_RETENTN SHEAPTHRES_SHR SOFTMAX SORTHEAP STAT_HEAP_SZ STMT_CONC STMTHEAP WLM_ADMISSION_CTRL\nParameters that support online updating: LOGSECOND\nDB20000I The TERMINATE command completed successfully.\n(*) Applying Db2 db cfg parameters for BLUDB\nupdate db cfg for BLUDB using APPLHEAPSZ 8192 AUTOMATIC AUTHN_CACHE_DURATION 10 AUTHN_CACHE_USERS 100 AUTO_DB_BACKUP OFF AUTO_DEL_REC_OBJ ON AUTO_MAINT ON AUTO_REORG OFF AUTO_REVAL DEFER...
{"level":"error","component":"server","subComponent":"GetDb2Health","caller":"[13]:db2.go:262:GetDb2Health()","timestamp":"2024-01-03T05:28:06Z","message":"1 MLNs found in MLN dist file, but only 0 db2sysc processes match"}
{"level":"error","component":"server","subComponent":"GetDb2Health","caller":"[13]:db2.go:262:GetDb2Health()","timestamp":"2024-01-03T05:29:06Z","message":"1 MLNs found in MLN dist file, but only 0 db2sysc processes match"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T05:51:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T06:01:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T06:11:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T06:31:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T06:51:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T07:11:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T07:51:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T08:01:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T08:21:10Z","message":"failed to remove expired locks"}
{"level":"error","caller":"[13]:k8s_v2.go:542:cleanUp()","error":"update failed: the server rejected our request due to an error in our request","timestamp":"2024-01-03T08:31:10Z","message":"failed to remove expired locks"}
```

**MAS Manage Maxinst pod log**
[dev-dev-manage-maxinst-5cbc974f78-pdrmb-manage-maxinst-maxinst.log](https://github.com/ibm-mas/ansible-devops/files/13816974/dev-dev-manage-maxinst-5cbc974f78-pdrmb-manage-maxinst-maxinst.log)

```
Press ENTER to continue . . .
Log file: Cleandb20240103083711.log
Connecting to: jdbc:db2://c-mas-dev-dev-manage-db2u-engn-svc.db2u.svc:50001/BLUDB:sslConnection=true;sslVersion=TLSv1.2;
Cleandatabase complete: Successful
Wed Jan 03 08:37:18 GMT 2024 --- Starting ----
BMXAA6806I - Reading the properties file maximo.properties.
BMXAA6814W - Maxinst Connection warning: com.ibm.db2.jcc.am.SqlWarning: DB2 SQL Warning: SQLCODE=0, SQLSTATE=00000, SQLERRMC=1;1208;DB2INST1;BLUDB;QDB2/LINUXX8664;18953;18953;0;1208;1;0;, DRIVER=4.32.28
java.lang.Exception: Invalid tablespace for -s and/or -t parameters. - MAXDATA
at psdi.configure.Maxinst.endSetupInstance(Maxinst.java:2598)
at psdi.configure.CommonShell.endSetup(CommonShell.java:1853)
at psdi.configure.CommonShell.setup(CommonShell.java:1353)
at psdi.configure.Maxinst.main(Maxinst.java:2725)
Invalid tablespace for -s and/or -t parameters. - MAXDATA Wed Jan 03 08:37:21 GMT 2024
Invalid tablespace for -s and/or -t parameters. - MAXDATA Wed Jan 03 08:37:21 GMT 2024
BMXAA6819I - Maxinst completed with errors. Wed Jan 03 08:37:21 GMT 2024
BMXAA6819I - Maxinst completed with errors. Wed Jan 03 08:37:21 GMT 2024
Maxinst/UpdateDB process ended with errors. Please check logs
Invalid tablespace for -s and/or -t parameters. - MAXDATA Wed Jan 03 08:37:21 GMT 2024
BMXAA6819I - Maxinst completed with errors. Wed Jan 03 08:37:21 GMT 2024
```

**Comment by ekambaraml** [comment]
I am using the default settings for all the components in this install. It seems the default configuration of DB2 is not sufficient. Please help to come up with right DB2/Database configuration to complete this install.

**Comment by whitfiea** [comment]
@ekambaraml can you check the log of the suite_db2_setup_manage task? It seems the role failed to create the tablespace. There is a change inflight to resolve that.

**Comment by ekambaraml** [comment]
suite-db2-setup-manage

[suite-db2-setup-manage.log](https://github.com/ibm-mas/ansible-devops/files/13819145/suite-db2-setup-manage.log)

**Comment by aroute** [comment]
@whitfiea this only breaks when using out of the box default configs, which uses system config scope. This does not break if the config scope is something other than system. 

The OOTB default is generally used for a design where the the DB2 is shared between the multiple apps of the suite (manage and monitor). If one were to setup multiple DB2s to setup databases separately for Manage and Monitor, then the maxinst process runs fine.

**Comment by ekambaraml** [comment]
I am able to resolve the DB2 tablespace creation issue with fix from @sachbalag . He is planning to merge his fix changes shortly.

**Comment by sachbalag** [comment]
Submitted PR https://github.com/ibm-mas/ansible-devops/pull/1121 for review. Awaiting feedback.
