### ISSUE TITLE
Bustardds, they killed Kenny

### ISSUE THREAD

**Issue by CryCostaCry** [ibm-mas/ansible-devops#1546]
### Collection version

from Nov 4

### Environment information

```console
Cloning into '/opt/app-root/src/masloc/ansible-devops'...
error: uds.crt doesn't exist in local filesystem
ansible-galaxy [core 2.12.7]
  config file = /opt/app-root/src/ansible.cfg
  configured module search path = ['/opt/ansible/library']
  ansible python module location = /opt/app-root/lib64/python3.9/site-packages/ansible
  ansible collection location = /opt/app-root/lib64/python3.9/site-packages/ansible_collections
  executable location = /opt/app-root/bin/ansible-galaxy
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
Using /opt/app-root/src/ansible.cfg as config file
Starting galaxy collection install process
```

### What happened?

the prosses used to go much further, it use to run about 40 min. I used it about 3 weeks ago.
Now it is 100% kaput after only 1 min or so. Dies with obscure error

ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'

You bet it is a bug :)

### Relevant log output

```shell
Calling Galaxy at https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/?limit=100&offset=100
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an
unexpected error when getting available versions of collection
community.general: '/api/v3/plugin/ansible/content/published/collections/index/
community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
the full traceback was:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'community.general'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/bin/ansible-galaxy", line 128, in <module>
    exit_code = cli.run()
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 569, in run
    return context.CLIARGS['func']()
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 86, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 1203, in execute_install
    self._execute_install_collection(
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 1230, in _execute_install_collection
    install_collections(
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/galaxy/collection/__init__.py", line 548, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/galaxy/collection/__init__.py", line 1364, in _resolve_depenency_map
```

**Comment by CryCostaCry** [comment]
So the fact that  https://github.com/evilADevil/mas-local rep has not been updated in last 2 years and the same script worked 3-4 weeks ago makes no difference?

**Comment by whitfiea** [comment]
@CryCostaCry the error is occurring now due to the change to the galaxy dependencies to add community.general here https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/galaxy.yml#L26. This is a valid change, however the script you are running from https://github.com/evilADevil/mas-local is running an old container image that is not able to install dependencies from ansible galaxy correctly.
