### ISSUE TITLE
SafetyWorkspace does not complete succeesfully

### ISSUE THREAD

**Issue by alequint** [ibm-mas/ansible-devops#72]
After several attempts, I have noticed SafetyWorkspace is not able to complete successfully.

- First error indicates IOT was not properly provisioned:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/15021471/143490569-93660fcc-402d-41fc-98f4-c1de4f5c4590.png">

- However, IoT is up and running and no pods indicating error.

- Then I tried the following workaround:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/15021471/143490685-51259661-d711-4457-bbce-9e57bae6b85f.png">

- And a different error message came up in safety-api pod after the operator reconcile:

```
context cleanup 7bb3854f-fedb-4cf0-a653-c79014aa595b did not finished
[2021-11-25T18:42:28.071Z] [[32mINFO[39m] [TenantController.provisionTenant] [6356f81e-95e5-4639-921a-c5792bdb521a] [New] Provision request
[2021-11-25T18:42:28.072Z] [[32mINFO[39m] [TenantController.provisionTenant] [6356f81e-95e5-4639-921a-c5792bdb521a] [New] {
  "name": "masdev",
  "guid": "masdev",
  "plan": "None",
  "planGuid": "None",
  "type": "internal",
  "tier": "None",
  "tenantId": "masdev",
  "tenantName": "masdev",
  "bluemixSpaceId": "None",
  "bluemixOrgId": "None",
  "contactName": "None",
  "contactEmail": "None"
}
[2021-11-25T18:42:28.074Z] [[32mINFO[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService.provisionTenant] Provisioning tenant masdev
[2021-11-25T18:42:28.102Z] [[32mINFO[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [TenantService.BaseService.update] Updating a tenant 1
[2021-11-25T18:42:28.103Z] [[32mINFO[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [TenantService.BaseService.get] Getting a tenant 1
[2021-11-25T18:42:28.217Z] [[32mINFO[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService.provisionTenant] First part of tenant (1) provisioning is successful.
[2021-11-25T18:42:28.219Z] [[32mINFO[39m] [OpsNotifier.notify] [6356f81e-95e5-4639-921a-c5792bdb521a] [1] Notifying ops
[2021-11-25T18:42:28.239Z] [[32mINFO[39m] [1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService._provisionTenantAsync] Starting second part of tenant provisioning
[2021-11-25T18:42:28.240Z] [[32mINFO[39m] [1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService._createDefaultDocs] Creating default config, jobs, shields
[2021-11-25T18:42:28.240Z] [[32mINFO[39m] [1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService._createDefaultDocs] Creating default roles
[2021-11-25T18:42:36.700Z] [[32mINFO[39m] [TenantController.getProvisioningStatus] [e45d1198-0af6-4049-b15e-040dacc71bc0] [1] Get status of tenant provisioning
[2021-11-25T18:42:36.727Z] [[32mINFO[39m] [1] [e45d1198-0af6-4049-b15e-040dacc71bc0] [InternalTenantService.getProvisioningStatus] Getting status of tenant provisioning
[2021-11-25T18:42:36.729Z] [[32mINFO[39m] [1] [e45d1198-0af6-4049-b15e-040dacc71bc0] [TenantService.BaseService.get] Getting a tenant 1
[2021-11-25T18:42:58.260Z] [[31mERROR[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService._provisionTenantAsync] Second part of tenant (1) provisioning failed. DriverException: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at DB2ExceptionConverter.convertException (/home/node/app/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at DB2ExceptionConverter.convertException (/home/node/app/node_modules/@iot4i/core/src/data/db2-driver/DB2ExceptionConverter.ts:36:18)
    at DB2Driver.convertException (/home/node/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at /home/node/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at DB2Driver.find (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at DB2Driver.findOne (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)
    at SqlEntityManager.findOne (/home/node/app/node_modules/@mikro-orm/core/EntityManager.js:227:22)
    at async Promise.all (index 1)
    at InternalTenantService._createDefaultDocs (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:347:5)
    at InternalTenantService._provisionTenantAsync (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:188:7)
previous KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at DB2Client.acquireConnection (/home/node/app/node_modules/knex/lib/client.js:348:26)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at DB2Connection.executeQuery (/home/node/app/node_modules/@mikro-orm/core/connections/Connection.js:56:25)
    at DB2Connection.execute (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:105:21)
    at QueryBuilder.execute (/home/node/app/node_modules/@mikro-orm/knex/query/QueryBuilder.js:300:21)
    at DB2Driver.find (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at DB2Driver.findOne (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)
    at SqlEntityManager.findOne (/home/node/app/node_modules/@mikro-orm/core/EntityManager.js:227:22)
    at async Promise.all (index 1)
    at InternalTenantService._createDefaultDocs (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:347:5)
    at InternalTenantService._provisionTenantAsync (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:188:7)
[2021-11-25T18:42:58.261Z] [[32mINFO[39m] [OpsNotifier.notify] [6356f81e-95e5-4639-921a-c5792bdb521a] [1] Notifying ops
[2021-11-25T18:42:58.262Z] [[32mINFO[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [TenantService.BaseService.update] Updating a tenant 1
[2021-11-25T18:42:58.262Z] [[32mINFO[39m] [-1] [6356f81e-95e5-4639-921a-c5792bdb521a] [TenantService.BaseService.get] Getting a tenant 1
[2021-11-25T18:42:58.264Z] [[33mWARN[39m] [xxxxxxxxx--No-Tenant-Id-xxxxxxxx] [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] [uncaughtException] Possibly Unhandled rejection:  DriverException: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at DB2ExceptionConverter.convertException (/home/node/app/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at DB2ExceptionConverter.convertException (/home/node/app/node_modules/@iot4i/core/src/data/db2-driver/DB2ExceptionConverter.ts:36:18)
    at DB2Driver.convertException (/home/node/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at /home/node/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at DB2Driver.find (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at DB2Driver.findOne (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)
    at SqlEntityManager.findOne (/home/node/app/node_modules/@mikro-orm/core/EntityManager.js:227:22)
    at async Promise.all (index 1)
    at InternalTenantService._createDefaultDocs (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:347:5)
    at InternalTenantService._provisionTenantAsync (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:188:7)
previous KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at DB2Client.acquireConnection (/home/node/app/node_modules/knex/lib/client.js:348:26)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at DB2Connection.executeQuery (/home/node/app/node_modules/@mikro-orm/core/connections/Connection.js:56:25)
    at DB2Connection.execute (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:105:21)
    at QueryBuilder.execute (/home/node/app/node_modules/@mikro-orm/knex/query/QueryBuilder.js:300:21)
    at DB2Driver.find (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at DB2Driver.findOne (/home/node/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:60:21)
    at SqlEntityManager.findOne (/home/node/app/node_modules/@mikro-orm/core/EntityManager.js:227:22)
    at async Promise.all (index 1)
    at InternalTenantService._createDefaultDocs (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:347:5)
    at InternalTenantService._provisionTenantAsync (/home/node/app/node_modules/@iot4i/core/src/services/InternalTenantService.ts:188:7)
[2021-11-25T18:42:58.283Z] [[32mINFO[39m] [1] [6356f81e-95e5-4639-921a-c5792bdb521a] [InternalTenantService._createDefaultDocs] Role administrator exists, skipping ...
```

- This is how SafetyWorkspace end up:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/15021471/143490827-31a6eba6-a558-4645-9e48-53845cb33cb7.png">

**Comment by paul-curran** [comment]
I think whatever the issue is here, the solution for it will likely be on the safety operator / application side rather than in this repo. We have an internal work item tracking this for the operator and will update this ticket when it is resolved.

**Comment by alequint** [comment]
The issue is being tracked in internal repo https://github.ibm.com/safety/tracker/issues/1562
