### ISSUE TITLE
TASK [ibm.mas_devops.suite_verify : Wait for Suite Components to be ready (60s delay)] failed

### ISSUE THREAD

**Issue by PuppyCode0723** [ibm-mas/ansible-devops#867]
When I execute `ansible-playbook ibm.mas_devops.oneclick_core`,  I got an error after retrying 50 times. And I go to console to get the detail, it tells me that milestonapi not ready.
![圖片](https://github.com/ibm-mas/ansible-devops/assets/24983804/ee8aeaa2-fb14-443b-935b-ef48ab42b43f)

I go to  milestonapi pods and get its logs, here is part of logs in milestoneapi pods.

```
2023-06-14 02:14:00,710   utils.catalog_helper            INFO     Initialising catalog_items cache
2023-06-14 02:14:00,811   utils.catalog_helper            INFO     Failure encountered while fetching catalog_items: An unhandled error was returned from the catalogmgr service: HTTPSConnectionPool(host='catalogmgr.mas-sno-core.svc', port=443): Max retries exceeded with url: /api/catalog/items (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9638a27670>: Failed to establish a new connection: [Errno -2] No address found'))
2023-06-14 02:14:00,812   milestonesapi                   ERROR    AIUMI0004E: Unable to initialize client and utilities: An unhandled error was returned from the catalogmgr service: HTTPSConnectionPool(host='catalogmgr.mas-sno-core.svc', port=443): Max retries exceeded with url: /api/catalog/items (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9638a27670>: Failed to establish a new connection: [Errno -2] No address found'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/site-packages/eventlet/support/greendns.py", line 539, in getaddrinfo
    raise socket.gaierror(socket.EAI_NONAME, 'No address found')
socket.gaierror: [Errno -2] No address found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9638a27670>: Failed to establish a new connection: [Errno -2] No address found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='catalogmgr.mas-sno-core.svc', port=443): Max retries exceeded with url: /api/catalog/items (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9638a27670>: Failed to establish a new connection: [Errno -2] No address found'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mas_catalog_client/exceptions.py", line 14, in inner_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mas_catalog_client/catalogmgr_client.py", line 35, in get_catalog_items
    resp = requests.get(f"{self._base_url}/catalog/items", cert=(self.client_cert, self.client_key), verify=self.server_ca)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
```
Here is my environment when I execute `ansible-playbook ibm.mas_devops.oneclick_core`
```
export DNS_PROVIDER=
export MAS_INSTANCE_ID=sno
export MAS_CONFIG_DIR=/mascli/masconfig
export PROMETHEUS_STORAGE_CLASS=nfs
export PROMETHEUS_USERWORKLOAD_STORAGE_CLASS=nfs
export GRAFANA_INSTANCE_STORAGE_CLASS=nfs
export MONGODB_STORAGE_CLASS=nfs
export UDS_STORAGE_CLASS=nfs
export PROMETHEUS_ALERTMGR_STORAGE_CLASS=nfs
export OCP_INGRESS_TLS_SECRET_NAME=router-certs-default
export UDS_CONTACT_EMAIL=XXX
export UDS_CONTACT_FIRSTNAME=XXX
export UDS_CONTACT_LASTNAME=XXX
export IBM_ENTITLEMENT_KEY=XXX
export MAS_HIDE_SUPERUSER_CREDENTIALS=True
export MONGODB_MEM_LIMITS=6Gi
export SLS_LICENSE_ID=XXX
export SLS_LICENSE_FILE=XXX
export MONGODB_REPLICAS=1
```
I'm not sure is there anything I miss, thx

**Comment by whitfiea** [comment]
@PuppyCode0723 The error is `socket.gaierror(socket.EAI_NONAME, 'No address found'` when trying to connect to  `catalogmgr.mas-sno-core.svc`. Does this service exist in your OCP and if so is the backing pod for this service in a ready state? If the service and pod are ok, then it looks like an Openshift DNS issue or an underlying DNS issue rather than something related to the ibm.mas_devops ansible collection.

**Comment by PuppyCode0723** [comment]
@whitfiea Thanks for replying, all of these parameters are generated by playbook, but why milestoneapi pods cannot find `catalogmgr.mas-sno-core.svc` host, should I add some parameters before executing ansible-playbook ?

**Comment by whitfiea** [comment]
@PuppyCode0723 You will need to check why the `catalogmgr.mas-sno-core.svc` service can't be found first. IT could be that the catalogmgr pod can't start correctly as the Mongo Service is not available due to the wrong StorageClass being used for example. You will need to run `oc get svc -n mas-sno-core` to see if the service is there, if it is then `oc get pod -n mas-sno-core` and see if the `catalogmgr` pod is present, ready and running.

**Comment by PuppyCode0723** [comment]
I think catalogmgr pod and its service are running and ready.
```
[core@00-0c-29-e6-5f-c5 ~]$ oc get svc -n mas-sno-core | grep catalogmgr
catalogmgr           ClusterIP   172.30.144.90    <none>        443/TCP   31h
[core@00-0c-29-e6-5f-c5 ~]$ oc get pod -n mas-sno-core | grep catalogmgr
sno-catalogmgr-65cffd7fff-vdrhx                         1/1     Running     0                31h
```
And here is my MongoDB status
```
[core@00-0c-29-e6-5f-c5 ~]$ oc get svc -n mongoce
NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
mas-mongo-ce-svc   ClusterIP   None         <none>        27017/TCP   32h
[core@00-0c-29-e6-5f-c5 ~]$ oc get pod -n mongoce
NAME                                           READY   STATUS    RESTARTS   AGE
mas-mongo-ce-0                                 2/2     Running   0          26h
mongodb-kubernetes-operator-57847b4858-cqrpj   1/1     Running   0          28h
```
All of these are running and ready.

**Comment by whitfiea** [comment]
@PuppyCode0723 thanks for the output. Yes that looks all fine to me, the service is there and the backing pod is ready and running. I don't think this is an issue with the MAS code or the ansible collection. This is more an issue with the OCP DNS and why the DNS service is not able to find the service that is present. I would recommend raising an support ticket with RedHat on this as to why the OpenShift DNS service is not able to resolve this.

**Comment by PuppyCode0723** [comment]
@whitfiea  I will ask RedHat for support.  Thanks for your help and have a nice day!
